version: '3.1'

services:
  backend:
  build:
  ports:
    - "5000:5000"
  depends_on:
    - db

  frontend:
    build: ../frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRE_PASSWORD: ${POSTGRE_PASSWORD}
      POSTGRE_DB: ${POSTGRE_DB}
    ports:
      - "5432:5432"