version: '3.1'

services:
  backend:
  build:
    context: ./backend
  ports:
    - "5000:5000"
  depends_on:
    - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRE_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRE_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"